# -*- coding: utf-8 -*-
"""cleandata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17YzZBfRpr2qJSDn_RgLX5TjsPqqagSAh
"""

import pandas as pd
import numpy as np
import os

WORKING_DIRECTORY = os.getcwd()
print(WORKING_DIRECTORY)

os.listdir(WORKING_DIRECTORY)

DATA_FILE = f'{WORKING_DIRECTORY}/data1.csv'
df = pd.read_csv(DATA_FILE)

df.info()

list(pd.isna(df).any(axis=1)).count(False)

complete_df = df[~pd.isna(df).any(axis=1)].reset_index(drop=True)
complete_df.head()

df.describe()

complete_df.to_csv('data_final_clean.csv')